x="python is a programing language"
print(x)
print(type(x))
print(len(x))
print("is" in x)
print("is" not in x)
print("was" not in x)
for i in x:
    print(i)
print(x[1])
print(x[8])
print(x[4:10])
print(x[4:])
print(x[:9])
print(x[-1])
print(x[-10:-1])
print(x[-4:])
print(x[:-8])
print(x.upper())
print(x.lower())
y="     he,llo"
print(y)
print(y.strip())
print(x.replace("python","java"))
print(y.split(","))
print(y+" "+x)
print(y.count("l" ))